/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StorySegment {
    level: bigint;
    narrative: string;
}
export interface Puzzle {
    id: bigint;
    cipherType: CipherType;
    storyPart: string;
    hint: string;
    difficulty: bigint;
    codedMessage: string;
    level: bigint;
    solution: string;
}
export interface Tutorial {
    tip: string;
    cipherType: CipherType;
    explanation: string;
    example: string;
}
export interface Achievement {
    badgeIcon: string;
    name: string;
    description: string;
    criteria: string;
}
export enum CipherType {
    caesarShift = "caesarShift",
    vigenere = "vigenere",
    symbolReplacement = "symbolReplacement",
    layered = "layered",
    playfair = "playfair",
    numberToLetter = "numberToLetter",
    morseCode = "morseCode",
    scrambledSentence = "scrambledSentence"
}
export interface backendInterface {
    addAchievement(name: string, description: string, badgeIcon: string, criteria: string): Promise<void>;
    addPuzzle(level: bigint, cipherType: CipherType, codedMessage: string, solution: string, hint: string, storyPart: string, difficulty: bigint): Promise<bigint>;
    addStorySegment(level: bigint, narrative: string): Promise<void>;
    addTutorial(cipherType: CipherType, explanation: string, example: string, tip: string): Promise<void>;
    getAchievement(name: string): Promise<Achievement>;
    getAllAchievements(): Promise<Array<Achievement>>;
    getAllPuzzles(): Promise<Array<Puzzle>>;
    getAllStorySegments(): Promise<Array<StorySegment>>;
    getPuzzle(id: bigint): Promise<Puzzle>;
    getPuzzlesByLevel(level: bigint): Promise<Array<Puzzle>>;
    getStorySegment(level: bigint): Promise<StorySegment>;
    getTutorial(cipherType: CipherType): Promise<Tutorial>;
}
import type { CipherType as _CipherType, Puzzle as _Puzzle, Tutorial as _Tutorial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAchievement(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPuzzle(arg0: bigint, arg1: CipherType, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPuzzle(arg0, to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPuzzle(arg0, to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStorySegment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStorySegment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStorySegment(arg0, arg1);
            return result;
        }
    }
    async addTutorial(arg0: CipherType, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTutorial(to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTutorial(to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async getAchievement(arg0: string): Promise<Achievement> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievement(arg0);
            return result;
        }
    }
    async getAllAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAchievements();
            return result;
        }
    }
    async getAllPuzzles(): Promise<Array<Puzzle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPuzzles();
                return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPuzzles();
            return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllStorySegments(): Promise<Array<StorySegment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStorySegments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStorySegments();
            return result;
        }
    }
    async getPuzzle(arg0: bigint): Promise<Puzzle> {
        if (this.processError) {
            try {
                const result = await this.actor.getPuzzle(arg0);
                return from_candid_Puzzle_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPuzzle(arg0);
            return from_candid_Puzzle_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPuzzlesByLevel(arg0: bigint): Promise<Array<Puzzle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPuzzlesByLevel(arg0);
                return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPuzzlesByLevel(arg0);
            return from_candid_vec_n3(this.uploadFile, this.downloadFile, result);
        }
    }
    async getStorySegment(arg0: bigint): Promise<StorySegment> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorySegment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorySegment(arg0);
            return result;
        }
    }
    async getTutorial(arg0: CipherType): Promise<Tutorial> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorial(to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid_Tutorial_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorial(to_candid_CipherType_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid_Tutorial_n8(this.uploadFile, this.downloadFile, result);
        }
    }
}
function from_candid_CipherType_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CipherType): CipherType {
    return from_candid_variant_n7(uploadFile, downloadFile, value);
}
function from_candid_Puzzle_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Puzzle): Puzzle {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_Tutorial_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tutorial): Tutorial {
    return from_candid_record_n9(uploadFile, downloadFile, value);
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cipherType: _CipherType;
    storyPart: string;
    hint: string;
    difficulty: bigint;
    codedMessage: string;
    level: bigint;
    solution: string;
}): {
    id: bigint;
    cipherType: CipherType;
    storyPart: string;
    hint: string;
    difficulty: bigint;
    codedMessage: string;
    level: bigint;
    solution: string;
} {
    return {
        id: value.id,
        cipherType: from_candid_CipherType_n6(uploadFile, downloadFile, value.cipherType),
        storyPart: value.storyPart,
        hint: value.hint,
        difficulty: value.difficulty,
        codedMessage: value.codedMessage,
        level: value.level,
        solution: value.solution
    };
}
function from_candid_record_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tip: string;
    cipherType: _CipherType;
    explanation: string;
    example: string;
}): {
    tip: string;
    cipherType: CipherType;
    explanation: string;
    example: string;
} {
    return {
        tip: value.tip,
        cipherType: from_candid_CipherType_n6(uploadFile, downloadFile, value.cipherType),
        explanation: value.explanation,
        example: value.example
    };
}
function from_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    caesarShift: null;
} | {
    vigenere: null;
} | {
    symbolReplacement: null;
} | {
    layered: null;
} | {
    playfair: null;
} | {
    numberToLetter: null;
} | {
    morseCode: null;
} | {
    scrambledSentence: null;
}): CipherType {
    return "caesarShift" in value ? CipherType.caesarShift : "vigenere" in value ? CipherType.vigenere : "symbolReplacement" in value ? CipherType.symbolReplacement : "layered" in value ? CipherType.layered : "playfair" in value ? CipherType.playfair : "numberToLetter" in value ? CipherType.numberToLetter : "morseCode" in value ? CipherType.morseCode : "scrambledSentence" in value ? CipherType.scrambledSentence : value;
}
function from_candid_vec_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Puzzle>): Array<Puzzle> {
    return value.map((x)=>from_candid_Puzzle_n4(uploadFile, downloadFile, x));
}
function to_candid_CipherType_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CipherType): _CipherType {
    return to_candid_variant_n2(uploadFile, downloadFile, value);
}
function to_candid_variant_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CipherType): {
    caesarShift: null;
} | {
    vigenere: null;
} | {
    symbolReplacement: null;
} | {
    layered: null;
} | {
    playfair: null;
} | {
    numberToLetter: null;
} | {
    morseCode: null;
} | {
    scrambledSentence: null;
} {
    return value == CipherType.caesarShift ? {
        caesarShift: null
    } : value == CipherType.vigenere ? {
        vigenere: null
    } : value == CipherType.symbolReplacement ? {
        symbolReplacement: null
    } : value == CipherType.layered ? {
        layered: null
    } : value == CipherType.playfair ? {
        playfair: null
    } : value == CipherType.numberToLetter ? {
        numberToLetter: null
    } : value == CipherType.morseCode ? {
        morseCode: null
    } : value == CipherType.scrambledSentence ? {
        scrambledSentence: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
