/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CipherType = IDL.Variant({
  'caesarShift' : IDL.Null,
  'vigenere' : IDL.Null,
  'symbolReplacement' : IDL.Null,
  'layered' : IDL.Null,
  'playfair' : IDL.Null,
  'numberToLetter' : IDL.Null,
  'morseCode' : IDL.Null,
  'scrambledSentence' : IDL.Null,
});
export const Achievement = IDL.Record({
  'badgeIcon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'criteria' : IDL.Text,
});
export const Puzzle = IDL.Record({
  'id' : IDL.Nat,
  'cipherType' : CipherType,
  'storyPart' : IDL.Text,
  'hint' : IDL.Text,
  'difficulty' : IDL.Nat,
  'codedMessage' : IDL.Text,
  'level' : IDL.Nat,
  'solution' : IDL.Text,
});
export const StorySegment = IDL.Record({
  'level' : IDL.Nat,
  'narrative' : IDL.Text,
});
export const Tutorial = IDL.Record({
  'tip' : IDL.Text,
  'cipherType' : CipherType,
  'explanation' : IDL.Text,
  'example' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAchievement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPuzzle' : IDL.Func(
      [IDL.Nat, CipherType, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addStorySegment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addTutorial' : IDL.Func([CipherType, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAchievement' : IDL.Func([IDL.Text], [Achievement], ['query']),
  'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAllPuzzles' : IDL.Func([], [IDL.Vec(Puzzle)], ['query']),
  'getAllStorySegments' : IDL.Func([], [IDL.Vec(StorySegment)], ['query']),
  'getPuzzle' : IDL.Func([IDL.Nat], [Puzzle], ['query']),
  'getPuzzlesByLevel' : IDL.Func([IDL.Nat], [IDL.Vec(Puzzle)], ['query']),
  'getStorySegment' : IDL.Func([IDL.Nat], [StorySegment], ['query']),
  'getTutorial' : IDL.Func([CipherType], [Tutorial], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CipherType = IDL.Variant({
    'caesarShift' : IDL.Null,
    'vigenere' : IDL.Null,
    'symbolReplacement' : IDL.Null,
    'layered' : IDL.Null,
    'playfair' : IDL.Null,
    'numberToLetter' : IDL.Null,
    'morseCode' : IDL.Null,
    'scrambledSentence' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'badgeIcon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'criteria' : IDL.Text,
  });
  const Puzzle = IDL.Record({
    'id' : IDL.Nat,
    'cipherType' : CipherType,
    'storyPart' : IDL.Text,
    'hint' : IDL.Text,
    'difficulty' : IDL.Nat,
    'codedMessage' : IDL.Text,
    'level' : IDL.Nat,
    'solution' : IDL.Text,
  });
  const StorySegment = IDL.Record({
    'level' : IDL.Nat,
    'narrative' : IDL.Text,
  });
  const Tutorial = IDL.Record({
    'tip' : IDL.Text,
    'cipherType' : CipherType,
    'explanation' : IDL.Text,
    'example' : IDL.Text,
  });
  
  return IDL.Service({
    'addAchievement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPuzzle' : IDL.Func(
        [IDL.Nat, CipherType, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addStorySegment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addTutorial' : IDL.Func(
        [CipherType, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAchievement' : IDL.Func([IDL.Text], [Achievement], ['query']),
    'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAllPuzzles' : IDL.Func([], [IDL.Vec(Puzzle)], ['query']),
    'getAllStorySegments' : IDL.Func([], [IDL.Vec(StorySegment)], ['query']),
    'getPuzzle' : IDL.Func([IDL.Nat], [Puzzle], ['query']),
    'getPuzzlesByLevel' : IDL.Func([IDL.Nat], [IDL.Vec(Puzzle)], ['query']),
    'getStorySegment' : IDL.Func([IDL.Nat], [StorySegment], ['query']),
    'getTutorial' : IDL.Func([CipherType], [Tutorial], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };