/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'badgeIcon' : string,
  'name' : string,
  'description' : string,
  'criteria' : string,
}
export type CipherType = { 'caesarShift' : null } |
  { 'vigenere' : null } |
  { 'symbolReplacement' : null } |
  { 'layered' : null } |
  { 'playfair' : null } |
  { 'numberToLetter' : null } |
  { 'morseCode' : null } |
  { 'scrambledSentence' : null };
export interface Puzzle {
  'id' : bigint,
  'cipherType' : CipherType,
  'storyPart' : string,
  'hint' : string,
  'difficulty' : bigint,
  'codedMessage' : string,
  'level' : bigint,
  'solution' : string,
}
export interface StorySegment { 'level' : bigint, 'narrative' : string }
export interface Tutorial {
  'tip' : string,
  'cipherType' : CipherType,
  'explanation' : string,
  'example' : string,
}
export interface _SERVICE {
  'addAchievement' : ActorMethod<[string, string, string, string], undefined>,
  'addPuzzle' : ActorMethod<
    [bigint, CipherType, string, string, string, string, bigint],
    bigint
  >,
  'addStorySegment' : ActorMethod<[bigint, string], undefined>,
  'addTutorial' : ActorMethod<[CipherType, string, string, string], undefined>,
  'getAchievement' : ActorMethod<[string], Achievement>,
  'getAllAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAllPuzzles' : ActorMethod<[], Array<Puzzle>>,
  'getAllStorySegments' : ActorMethod<[], Array<StorySegment>>,
  'getPuzzle' : ActorMethod<[bigint], Puzzle>,
  'getPuzzlesByLevel' : ActorMethod<[bigint], Array<Puzzle>>,
  'getStorySegment' : ActorMethod<[bigint], StorySegment>,
  'getTutorial' : ActorMethod<[CipherType], Tutorial>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];